import type { Metadata } from "next";
import "./globals.css";
import {Roboto} from "next/font/google";

export const metadata: Metadata = {
  title: "Shoehaven",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} `}
      >
        {children}
      </body>
    </html>
  );
}
